#!/bin/bash

# Update the system
echo "[TASK 1] Updating the system"
yum update -y >/dev/null 2>&1

# Install desired packages
echo "[TASK 2] Installing desired packages"
yum install -y -q vim redhat-lsb-core net-tools bind-utils >/dev/null 2>&1

# Set up global aliases and exports
echo "[TASK 3] Creating global aliases and functions"
cat >>/etc/bashrc <<EOF
# Generated by Vagrant
alias vi='vim'
alias sudo='sudo '
export EDITOR=vim
export TERM=xterm
# Generated by Vagrant
EOF

echo "colorscheme elflord" >> /etc/vimrc

# Enable password authentication
echo "[TASK 4] Enabling password authentication in sshd config"
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd

# Disable SELinux
echo "[TASK 5] Disable SELinux"
setenforce 0
sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

# Set Root password
echo "[TASK 6] Set root password"
echo "admin" | passwd --stdin root >/dev/null 2>&1

# Disable and stop firewalld
echo "[TASK 5] Disable and stop firewalld"
systemctl disable firewalld >/dev/null 2>&1
systemctl stop firewalld

# Update hosts file
echo "[TASK 6] Update /etc/hosts file"
cat >>/etc/hosts<<EOF
192.168.50.26 kubernetes.eduami.org kubernetes
EOF


# install git
echo "[TASK 7] install git"
yum install -y git

# htop utility
echo "[TASK 8] install htop"
yum install -y epel-release
yum install -y htop

# install java
echo "[TASK 9] install java"
yum install -y java

# install maven
echo "[TASK 10] install maven"
yum install -y maven

# install tree
echo "[TASK 11] install tree"
yum install -y tree

# install docker
# SET UP THE REPOSITORY
echo "[TASK 12] Install docker"
yum-config-manager     --add-repo     https://download.docker.com/linux/centos/docker-ce.repo
yum install -y docker-ce docker-ce-cli containerd.io
systemctl enable docker
systemctl start docker

# install docker compose
echo "[TASK 13] Install docker compose"
yum install -y docker-compose


# install wget
echo "[TASK 14] Install curl"
yum install -y wget

# install unzip
echo "[TASK 15] Install unzip"
yum install -y unzip

# install springtools
echo "[TASK 16] Install springtools"
wget https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/2.3.3.RELEASE/spring-boot-cli-2.3.3.RELEASE-bin.zip
unzip spring-boot-cli-2.3.3.RELEASE-bin.zip

# Install kubectl on Linux
echo "[TASK 17] Install kubectl binary with curl on Linux"
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
yum install -y kubectl

# Installing minikube
echo "[TASK 18] Install kubectl binary with curl on Linux"
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
mkdir -p /usr/local/bin/
install minikube /usr/local/bin/

# Start minikube with out hypervisor
echo "[TASK 19] Start minikube with out hypervisor"
minikube start --driver=none